version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "mattermost/cloud-sre"
    open-pull-requests-limit: 5
    groups:
      Github Actions updates:
        applies-to: version-updates
        dependency-type: production
    schedule:
      # Check for updates to GitHub Actions every week
      day: "monday"
      time: "10:00"
      interval: "weekly"
