# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
    disable:
      - fieldalignment

linters:
  disable-all: true
  enable:
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - copyloopvar
    - staticcheck
    - unconvert
    - unused
