name: Build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.7

    - name: check dependencies
      run: make check-deps

    - name: Run build
      run: make package

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: push-proxy-binaries
        retention-days: 5
        path: |
          ./dist/*.tar.gz
          ./dist/checksums.txt
